#!/bin/sh
# This file is automatically generated by dependabot, please do not modify it manually!!!
#
# Dependency upgrades applied from alauda-v1.42.3 vs upstream v1.42.3.
# Security and compatibility bumps for Go modules.
go get golang.org/x/crypto@v0.53.0
go get golang.org/x/net@v0.55.0
go get golang.org/x/sync@v0.21.0
go get golang.org/x/sys@v0.46.0
go get golang.org/x/text@v0.38.0
go get golang.org/x/mod@v0.36.0
go get golang.org/x/exp@v0.0.0-20260410095643-746e56fc9e2f
go get golang.org/x/tools@v0.45.0
go get github.com/go-git/go-git/v5@v5.19.1
go get github.com/go-git/go-billy/v5@v5.9.0
go get github.com/hashicorp/go-getter@v1.8.6
go get github.com/go-jose/go-jose/v4@v4.1.4

go mod tidy
go mod download -x
